### ISSUE TITLE
只是用ocr识别出来文字，那么是如何做的映射关系转换

### ISSUE THREAD

**Issue by MaaaxYang** [derek-s/Python-Tianyancha#11]
我不太会Python 所以是用Java写的，请教一下 转换思路 比如如何把 “万古钱” 转换成 “人民币”

**Comment by derek-s** [comment]
@MaaaxYang 我这边没有做映射转换，考虑到字体替换反爬虫是会经常更换字体，而且我这边是练手的项目，并没有长期的采集，所以就没有做映射转换存储这一块的东西。
