### ISSUE TITLE
-psm 改成 --psm

### ISSUE THREAD

**Issue by dingar** [derek-s/Python-Tianyancha#12]
> Traceback (most recent call last):
>   File "main3.py", line 484, in <module>
>     main(logfile, excel)
>   File "main3.py", line 433, in main
>     maping, fontname = gettycfont()
>   File "main3.py", line 307, in gettycfont
>     return getmaping("tyc-num.ttf"), fontpath_name[0]
>   File "main3.py", line 367, in getmaping
>     num = pytesseract.image_to_string(fontimage, config="-psm 6")
>   File "D:\Users\dingar\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 125, in image_to_string
>     raise TesseractError(status, errors)
> pytesseract.pytesseract.TesseractError: (1, "Error, unknown command line argument '-psm'")

经Google，需要把 `-psm` 改成 `--psm` 。

**Comment by derek-s** [comment]
@dingar 可能是你pytesseract的版本比我开发时用的高一些，我这边开发时候是可以直接跑的。
