### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by sirliu** [derek-s/Python-Tianyancha#15]
运行时报错
`pytesseract.pytesseract.TesseractError: (1, "Error, unknown command line argument '-psm'")`

现在百度ORC每天能查50000，高精度也有500，希望可以增加选择使用百度ORC的选择。

虽然还没能用上，看着洋洋洒洒这么多代码，还是要感谢作者，辛苦了，兄弟！

**Comment by derek-s** [comment]
@sirliu 报错看上去似乎是你使用的Tesseract不识别psm这个参数，你用的是什么版本？
接入百度的OCR的话，你可以找一下百度OCR的文档，看怎么使用和接入。
