### ISSUE TITLE
有点问题

### ISSUE THREAD

**Issue by leondyn** [derek-s/Python-Tianyancha#17]
报这个是什么情况

https://static.tianyancha.com/fonts-styles/css/6b/6bc550f4/font.css
download font
https://static.tianyancha.com/fonts-styles/fonts/6b/6bc550f4/tyc-num.ttf
处理数字加密映射
0
1
2
3
4
5
6
7
8
.
0
https://static.tianyancha.com/fonts-styles/css/6b/6bc550f4/font.css
https://static.tianyancha.com/fonts-styles/fonts/6b/6bc550f4/tyc-num.ttf
encrypt not change
Message: unknown field `ms`, expected one of `implicit`, `pageLoad`, `script` at
 line 1 column 5

error wait 30 secs tyc_data1

**Comment by derek-s** [comment]
可能是selenium的问题，善用搜索自己研究一下吧。
