### ISSUE TITLE
爬取太多还是会有验证码的

### ISSUE THREAD

**Issue by ybbtuubj** [derek-s/Python-Tianyancha#5]
咳咳，现在爬取太多也会封了，m.tianyancha.com已经会出验证码了

**Comment by derek-s** [comment]
@ybbtuubj 自己控制一下频率试试看，我这边测试1W条不会出验证码。

**Comment by ybbtuubj** [comment]
嗯，你说的对，频率确实不能太快，可不太快又很慢，确实要换动态拨号之类的，我把你这个改成分布式的，现在爬取几下，就弹手机短信验证码。

**Comment by derek-s** [comment]
@ybbtuubj 这个没有啥太好的办法，只能是考虑用代理池或者动态拨号。我还没遇到过手机短信验证码的页面是什么样子的。
