### ISSUE TITLE
Import Error: cannot import name 'version'

### ISSUE THREAD

**Issue by qzcool** [derek-s/Python-Tianyancha#6]
Hi，感谢开源这个爬虫。我在使用Python 3.6运行时候发现了如下问题，我简单在StackOverflow上搜到了这个[答案](https://stackoverflow.com/questions/25121356/python-importerror-cannot-import-name-version)，可能有帮助。另外，是否可以使用pandas的DataFrames来做数据存储的媒介呢？

```
(base) D:\GitHub` Documents\Python-Tianyancha>python main3.py
Traceback (most recent call last):
  File "main3.py", line 17, in <module>
    from PIL import Image, ImageFont, ImageDraw
  File "D:\Anaconda\lib\site-packages\PIL\__init__.py", line 14, in <module>
    from . import version
ImportError: cannot import name 'version'
```

**Comment by LiWeiMr** [comment]
您好，我看了您的代码，但是中间出了一些小问题，因为像天眼查这种网站经常会进行改进，所以我不知道我现在遇到的问题您当时是否遇到。主要还是问下您的这部分代码
![image](https://user-images.githubusercontent.com/30134415/38127373-7a74b1c8-3428-11e8-917e-c073f5f20217.png)
找的应该是“https://static.tianyancha.com/m-require-js/public/styles/main-bf4c109d10.css”这个链接，如图：
![image](https://user-images.githubusercontent.com/30134415/38127426-a6fb8c80-3428-11e8-8dbf-c0d34935e841.png)
这个文件里面应该并没有您想要的ttf 文件吧，然后我便找到了这个文件：
![image](https://user-images.githubusercontent.com/30134415/38127457-c6df5928-3428-11e8-85c2-23dd239c251e.png)
里面的内容是这样的
![image](https://user-images.githubusercontent.com/30134415/38127470-d19ab31c-3428-11e8-8329-bd36e34d89e6.png)，不知道是不是你所匹配的文件，目前我还在调试您的代码，请您看到回复一下我所说的问题

**Comment by derek-s** [comment]
@LiWeiMr 我在开发的时候没有遇到这个问题，不过可能是后面他们官方又改掉了。
你找到的这个字体文件应该是对的。我开发时匹配的字体文件就是这样的。
这块还是要调试一下，主要是映射表映射出来的跟正常的原始数字是不是一样的。我看字体大小有变化，所以OCR识别这一块可能你也要调试一下看看。

**Comment by tlhbjfunny** [comment]
谢谢共享这个爬虫程序！调试如下错误，不知道是哪里问题？万分感谢！
Message: Unable to find a matching set of capabilities

https://static.tianyancha.com/fonts-styles/css/67/67d3b4fb/font.css
download font
https://static.tianyancha.com/fonts-styles/fonts/67/67d3b4fb/tyc-num.ttf
处理数字加密映射
0
Traceback (most recent call last):
  File "E:/python/Projects/tianyancha/main3.py", line 484, in <module>
    main(logfile, excel)
  File "E:/python/Projects/tianyancha/main3.py", line 433, in main
    maping, fontname = gettycfont()
  File "E:/python/Projects/tianyancha/main3.py", line 307, in gettycfont
    return getmaping("tyc-num.ttf"), fontpath_name[0]
  File "E:/python/Projects/tianyancha/main3.py", line 367, in getmaping
    num = pytesseract.image_to_string(fontimage, config="-psm 6")
  File "E:\python\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "E:\python\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "E:\python\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "E:\python\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by derek-s** [comment]
@tlhbjfunny 你是不是没有安装tesseract-ocr？

**Comment by tlhbjfunny** [comment]
下面报错是不是没有输入的xls的公司名称文件啊？默认的cxgs.xlsx，表格式有没有要求呢？github里要是能放一个cxgs.xlsx的示例文件就好了。

E:\python\Anaconda3\python.exe E:/python/Projects/tianyancha/main3.py
Message: Unable to find a matching set of capabilities

https://static.tianyancha.com/fonts-styles/css/67/67d3b4fb/font.css
download font
https://static.tianyancha.com/fonts-styles/fonts/67/67d3b4fb/tyc-num.ttf
处理数字加密映射
0
1
2
3
4
5
6
7
8
.
open excel file failed [Errno 2] No such file or directory: 'cxgs.xlsx'
read sheet failed 'NoneType' object has no attribute 'sheets'
Traceback (most recent call last):
  File "E:/python/Projects/tianyancha/main3.py", line 484, in <module>
    main(logfile, excel)
  File "E:/python/Projects/tianyancha/main3.py", line 447, in main
    for sheet in readsheets('cxgs.xlsx'):
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1

**Comment by tlhbjfunny** [comment]
建了一个excel文件，里面定格写入了一个公司名，运行后有输出excle文件，但除了表头，内容是空的。代码运行错误提示如下：

E:\python\Anaconda3\python.exe E:/python/Projects/tianyancha/main3.py
Message: Unable to find a matching set of capabilities

https://static.tianyancha.com/fonts-styles/css/67/67d3b4fb/font.css
download font
https://static.tianyancha.com/fonts-styles/fonts/67/67d3b4fb/tyc-num.ttf
处理数字加密映射
0
1
2
3
4
5
6
7
8
.
Traceback (most recent call last):
  File "E:/python/Projects/tianyancha/main3.py", line 484, in <module>
    main(logfile, excel)
  File "E:/python/Projects/tianyancha/main3.py", line 478, in main
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment

Process finished with exit code 1

**Comment by derek-s** [comment]
这个项目本身就是我自己练手的项目，开源是为了分享学习，而且现在天眼查已经开始使用中文字体替换的反爬虫方式，OCR识别的正确率不是特别高，建议您自行解决问题，csgx文件内容有表头，就一列，没什么别的格式。
drvier的问题，请您阅读README.md

或者您可以考虑付费解决问题。

**Comment by tlhbjfunny** [comment]
谢谢！现在运行倒是没有报错信息了，但是结果表内容为空，我尝试将
 #tycurl = "https://m.tianyancha.com/search?key=" + keyword + "&checkFrom=searchBox"
这句直接给keyword赋值：
 tycurl = "https://m.tianyancha.com/search?key=" + '宁波凌科教育培训学校' + "&checkFrom=searchBox"
结果还是为空。
您那边能正常运行吗？

**Comment by derek-s** [comment]
![20180515112749](https://user-images.githubusercontent.com/2220273/40035170-157de8fa-5833-11e8-9d8f-c84fb8df7949.png)

刚刚试过，正常运行。因为中文替换反爬虫的问题，所以经营范围的中文有些错误。
我没有注意页面上的联系人和联系电话，也没有去看，理论上应该是可以爬。

**Comment by tlhbjfunny** [comment]
![cxgs](https://user-images.githubusercontent.com/19375167/40035797-18112ffc-5836-11e8-9788-253a5352cba1.png)
![debeg](https://user-images.githubusercontent.com/19375167/40035807-259ae53c-5836-11e8-929e-08106e792502.png)
我也用相同的公司查询，为啥我这边内容空啊？
刚试过在表中多加几个企业，但结果表只有企业名称，公司状态为暂无信息，其他列都为空。

**Comment by derek-s** [comment]
@tlhbjfunny 我在上面的回复里已经说了csgx这个文件有表头。像你现在这种没有表头的表，要么空一行，要么修改代码，从第一行就开始读。
添加多个企业的，要么是搜索名称对不上，要么就是OCR识别公司名称的时候识别出错误。
而且你添加的这个公司名称也是错的，并不是我这边测试使用的公司名称。

**Comment by tlhbjfunny** [comment]
谢谢耐心指导，后面考虑付费。希望有一个稳定的系统。
