### ISSUE TITLE
程序问题

### ISSUE THREAD

**Issue by yangshaojie0123** [derek-s/Python-Tianyancha#8]
FileNotFoundError: [WinError 2] 系统找不到指定的文件。已经安装需要的依赖和语料库了，为什么还是报这个错误呢？谢谢您的回答。

**Comment by yangshaojie0123** [comment]
已经测试了path环境且cmd环境下能够正常运行tesseract，我看到了tesseract.py代码里边的cmd=“tesseract”代码，觉得不应该是环境变量问题。在调试过程中，会不会是我的drvier存在版本问题也会报这个错误，我的tesseract确认是没有问题的，且安装了中文语料库，但是这个错误有些感觉奇怪。

**Comment by yangshaojie0123** [comment]
1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\eng.traineddata。您好，刚才执行程序又出现了这个新的问题。

**Comment by derek-s** [comment]
1. 你第一个问题没有贴出具体的抛错信息，我只能猜测是什么问题并给你一个解决方向、
2. 报错信息写的很明白，无法打开 `Error opening data file \Program Files (x86)\Tesseract-OCR\eng.traineddata` 你确定你安装的没有问题？
我这边刚开一台Win10的虚拟机测试，tessdata都是在以下路径的：
`C:\Program Files (x86)\Tesseract-OCR\tessdata`

![20180517123436](https://user-images.githubusercontent.com/2220273/40156938-d5d0d58a-59ce-11e8-8b7c-70b2020644cc.png)
